[package]
name = "egui-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.22.0"
eframe = "0.22.0"

serde = "1.0.159"
serde_derive = "1.0.159"
serde_json = "1.0.95"

rand = "0.8.5"